version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3366:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=cool
      - MYSQL_PASSWORD=password
      - MYSQL_USER=vladi
      - MYSQL_DATABASE=app